### ISSUE TITLE
dtype `numpy.int` has been deprecated since `numpy==1.20.0` and raises now an exception

### ISSUE THREAD

**Issue by wessm** [jasperroebroek/pyspatialstats#1]
`focal_stats` apparently uses the dtype `numpy.int`, which [raises an exception](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations) since `numpy==1.24.0`.

To solve this issue, either 
* `numpy.int` can be replaced with `int`,
* or the requirements.txt is updated to require a numpy version `<1.24.0`.

**Comment by jasperroebroek** [comment]
Thanks for letting me know. I will update the code accordingly!
